#!/usr/bin/env python3
"""
Agent Manager Module
Handles agent lifecycle management in a modular way.
"""

import yaml
from pathlib import Path
from typing import Dict, Any
from pydantic import BaseModel


class AgentDefinition(BaseModel):
    """Agent definition model"""
    name: str
    description: str
    port: int
    ollama_host: str = "http://ollama:11434"
    model: str = "llama3.2"
    temperature: float = 0.7
    max_tokens: int = 4096
    capabilities: list[str] = []
    system_prompt: str


class AgentManager:
    """
    Manages agent definitions in a modular way.
    Stores agent specs as YAML files that can be deployed separately.
    """

    def __init__(self, definitions_dir: Path):
        self.definitions_dir = Path(definitions_dir)
        self.definitions_dir.mkdir(parents=True, exist_ok=True)

    def save_agent_definition(self, agent: AgentDefinition) -> str:
        """
        Save agent definition as YAML file.
        This file can then be deployed using external tools.
        """
        definition = {
            "agent": {
                "name": agent.name,
                "description": agent.description,
                "version": "1.0.0"
            },
            "deployment": {
                "port": agent.port,
                "ollama_host": agent.ollama_host,
                "model": agent.model,
                "temperature": agent.temperature,
                "max_tokens": agent.max_tokens
            },
            "capabilities": agent.capabilities,
            "system_prompt": agent.system_prompt
        }

        filepath = self.definitions_dir / f"{agent.name}.yml"
        with open(filepath, "w") as f:
            yaml.dump(definition, f, default_flow_style=False, sort_keys=False)

        return str(filepath)

    def list_agent_definitions(self) -> list[Dict[str, Any]]:
        """List all agent definitions"""
        definitions = []
        for filepath in self.definitions_dir.glob("*.yml"):
            try:
                with open(filepath, "r") as f:
                    data = yaml.safe_load(f)
                    definitions.append({
                        "name": data["agent"]["name"],
                        "description": data["agent"].get("description", ""),
                        "port": data["deployment"]["port"],
                        "status": "defined",  # Not yet deployed
                        "file": filepath.name
                    })
            except Exception as e:
                definitions.append({
                    "name": filepath.stem,
                    "error": str(e),
                    "file": filepath.name
                })
        return definitions

    def get_agent_definition(self, name: str) -> Dict[str, Any]:
        """Get a specific agent definition"""
        filepath = self.definitions_dir / f"{name}.yml"
        if not filepath.exists():
            return None

        with open(filepath, "r") as f:
            return yaml.safe_load(f)

    def update_agent_definition(self, agent: AgentDefinition) -> str:
        """
        Update an existing agent definition.
        Returns the filepath of the updated definition.
        """
        filepath = self.definitions_dir / f"{agent.name}.yml"
        if not filepath.exists():
            raise ValueError(f"Agent definition '{agent.name}' not found")
        
        # Save the updated definition (reuse save logic)
        return self.save_agent_definition(agent)

    def delete_agent_definition(self, name: str) -> bool:
        """Delete an agent definition"""
        filepath = self.definitions_dir / f"{name}.yml"
        if filepath.exists():
            filepath.unlink()
            return True
        return False

    def generate_deploy_script(self, name: str) -> str:
        """
        Generate a bash script to deploy this agent.
        Returns the script content.
        """
        definition = self.get_agent_definition(name)
        if not definition:
            raise ValueError(f"Agent definition '{name}' not found")

        agent_name = definition["agent"]["name"]
        description = definition["agent"]["description"]
        port = definition["deployment"]["port"]
        model = definition["deployment"]["model"]
        temperature = definition["deployment"]["temperature"]
        max_tokens = definition["deployment"]["max_tokens"]
        capabilities = definition.get("capabilities", [])
        system_prompt = definition["system_prompt"]

        env_prefix = agent_name.upper().replace("-", "_")

        script = f'''#!/bin/bash
# Deploy {agent_name} agent
# Generated by Agent Manager

set -e

echo "Deploying agent: {agent_name}"

# Create agent directory
mkdir -p agents/{agent_name}
mkdir -p runtime/context/{agent_name}

# Create config.yml
cat > agents/{agent_name}/config.yml << 'EOF'
agent:
  name: {agent_name}
  description: {description}
  version: 1.0.0

capabilities:
{yaml.dump(capabilities, default_flow_style=False, indent=2)}

options:
  temperature: {temperature}
  num_predict: {max_tokens}
  top_k: 40
  top_p: 0.9
  repeat_penalty: 1.1
EOF

# Create prompt.txt
cat > agents/{agent_name}/prompt.txt << 'EOF'
{system_prompt}
EOF

# Update .env file
if ! grep -q "{env_prefix}_PORT" .env; then
  echo "" >> .env
  echo "# ----------------------------------------------------------------------------" >> .env
  echo "# {agent_name.title().replace('-', ' ')} Agent Configuration" >> .env
  echo "# ----------------------------------------------------------------------------" >> .env
  echo "{env_prefix}_PORT={port}" >> .env
  echo "{env_prefix}_MODEL={model}" >> .env
  echo "{env_prefix}_TEMPERATURE={temperature}" >> .env
  echo "{env_prefix}_MAX_TOKENS={max_tokens}" >> .env
fi

# Generate docker-compose service entry
echo "
To complete the deployment, add this to docker-compose.yml:

  {agent_name}:
    build:
      context: ./agents/base
      dockerfile: Dockerfile
    container_name: agent-{agent_name}
    restart: unless-stopped
    ports:
      - \\"${{{env_prefix}_PORT:-{port}}}:8000\\"
    volumes:
      - ./agents/{agent_name}/prompt.txt:/app/prompt.txt:ro
      - ./agents/{agent_name}/config.yml:/app/config.yml:ro
      - ./runtime/context/{agent_name}:/app/context
    networks:
      - agent-network
    environment:
      - AGENT_NAME={agent_name}
      - OLLAMA_HOST=${{OLLAMA_HOST:-http://ollama:11434}}
      - MODEL_NAME=${{{env_prefix}_MODEL:-{model}}}
      - TEMPERATURE=${{{env_prefix}_TEMPERATURE:-{temperature}}}
      - MAX_TOKENS=${{{env_prefix}_MAX_TOKENS:-{max_tokens}}}
    healthcheck:
      test: [ \\"CMD\\", \\"curl\\", \\"-f\\", \\"http://localhost:8000/health\\" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

Then run: docker compose up -d --build {agent_name}
"

echo "Agent files created successfully!"
echo "Review the generated files in agents/{agent_name}/"
'''

        return script
